language: python
python: 3.8
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
  - pip install pytest black==19.10b0
language: python
script: black hassrelease tests --check --fast && pytest
